name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r backend/requirements.txt -r frontend/requirements.txt
      - run: pip install black ruff mypy pytest
      - run: ruff backend/app frontend
      - run: black --check backend/app frontend
      - run: mypy backend/app
      - run: pytest -q
